name: Publicar Fierrolais Racing

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  crear-lanzamiento:
    runs-on: windows-latest

    steps:
      - name: 📥 Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: 📦 Empaquetar el juego
        run: Compress-Archive -Path bin, assets, README.md -DestinationPath FierrolaisRacing_Windows.zip

      - name: 🚀 Publicar en GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: FierrolaisRacing_Windows.zip
          name: Fierrolais Racing ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}